apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: invalid-policy
  namespace: test
spec:
  podSelector:
    matchLabels:
      app: web
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: frontend
    - from:
        - namespaceSelector:  # Missing required fields
